### PR TITLE
GitHub action workflow

### LINKED ISSUE #7: Versioning and Tests
Since you mentioned you are working on a significant new feature branch, I thought I would bring up some nice-to-haves. You have no doubt thought of many or all of them already, so this issue is more to get an idea of what your plans are.

## Versioning

I hope you will label a version before merging a major new feature branch. It makes it easier for outside projects to reference the project with a submodule. Some projects use tags, others use branches, and some use both. I have found version branches to be particularly helpful because it is easy to find them, especially in a git GUI frontend.

At some point it may become necessary to drop support for C++17. Or it may be that you would like to refactor for C++23 eventually and drop C++20. All of this can be easily controlled and documented with version branches.

## Tests

I did not run the tests yesterday on C++17, because there is no build script for them. I'm guessing you may have one privately. It might be nice to have a test script in the repo that builds and runs the test on any supported C++.

It might also be nice to set up a GitHub Action that builds and runs the tests on every PR to `master`. This is something I might be able to contribute if you are interested.

### PR DESCRIPTION
**Pull request by rpatters1**
Resolves #7 

This PR request adds a workflow that runs every time a PR is opened against the `master` branch and every time there is a push to the `master` branch. The results appear when this PR is created and for every PR thereafter as long as the workflow is in place.

The workflow builds and runs `ezgz_test` on Ubuntu (GCC), macOS (AppleClang), and Windows (MSVC) for both C++20 and C++17. 

I recommend putting in place a branch protection rule for `master` that requires this workflow to run successfully before a PR can be merged. Here are the steps (courtesy of ChatGPT):

To require that a GitHub Actions workflow completes successfully before a pull request (PR) can be merged, you need to set up **branch protection rules** in the repository settings. These rules enforce that certain checks, like your workflow runs, pass before allowing a PR to be merged.

Here's how you can set it up:

### Steps to Require a Workflow Pass Before Merging a PR:

1. **Go to the Repository Settings**:
   - Navigate to the repository where you want to enforce the rule.
   - Click on the `Settings` tab at the top of the repository page.

2. **Set Up Branch Protection Rules**:
   - In the left-hand menu, click on **Branches** under the "Code and automation" section.
   - Under "Branch protection rules", click **Add rule** (or edit an existing rule if you already have one).

3. **Choose the Branch to Protect**:
   - In the **Branch name pattern** field, specify the branch you want to protect. Usually, you would protect the `main` or `master` branch (the default branch).
   - For example, enter `main` to protect the `main` branch.

4. **Enable Status Checks**:
   - Check the box for **Require status checks to pass before merging**.
   - This will allow you to specify which checks must pass before a PR can be merged.

5. **Select the Workflow(s) to Require**:
   - After enabling **Require status checks to pass before merging**, you'll see an option to select which checks are required.
   - In this list, look for your workflow. The workflow that runs in the PR (defined in your `.github/workflows/` directory) should appear in this list.
   - Select the checkbox next to the workflow you want to require to pass. It will typically be listed by the name of the job in your workflow file (e.g., `CI`, `build`, etc.).

6. **Optional: Additional Settings**:
   - You can also enable other settings like:
     - **Require branches to be up to date before merging** (ensures that the PR is up to date with the target branch).
     - **Include administrators** (forces admins to comply with the branch protection rules).

7. **Save the Rule**:
   - After configuring the settings, click **Create** or **Save changes**.

### Example Configuration:
If you configured your GitHub Actions workflow to run on pull requests to the `main` branch, and you named the job `build`, you'll see `build` as an option in the **Status checks** section of the protection rule settings.

### Summary:
By setting up branch protection rules, you ensure that a pull request cannot be merged unless the workflow (or specific jobs within it) completes successfully. This is a great way to enforce CI/CD best practices and prevent unverified code from being merged.

### CODE REVIEW

**Comment by rpatters1** [comment]
Actually, it looks like the workflow will not run for the first time until the PR is merged.

**Comment by Dugy** [comment]
I decided that I will trust you that it's done correctly and I merged it, and the build completed successfully. Thanks for the help on this.

**Comment by rpatters1** [comment]
I'm glad to help. You can see the output from each job by drilling down into the workflow and then each job. That lets you see logs where it built and ran `ezgz_test` in each configuration.

If you want a detailed explanation of the workflow script, I would suggest copying the entire thing into ChatGPT and asking for a step-by-step explanation.

You may have to modify it if you

- refactor the directory structure of `ezgz`.
- add dependencies to the build. If you need dependencies that are not pre-installed, you can add a step to install them with the appropriate package manager: `brew` (mac), `apt` (ubuntu), `vcpkg` (win), `npm`, etc. [Here is the info](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners) on the GitHub runners that run workflows.

You will note the addition of `shell: bash` on some of the steps. That forces Windows to run the step on `bash`. Otherwise it would run the step in `powershell` and fail because those are `bash` commands and not `powershell` commands. It doesn't hurt macOS or Ubuntu, because they use `bash` anyway.

Most of the C++ open source projects I've worked with seem to use [Google Test](https://github.com/google/googletest/releases) for their automated test apps. That's a possible future refactor, if your interest in the project continues.

**Comment by rpatters1** [comment]
If you ever need to test changes to this workflow or to a new workflow, you can add the feature branch to the list of push branches at the top. Then the workflow runs every time you push the feature branch. That is, in fact, how I tested this one. (My forks has stack of at least 20 commits that I needed to get it to work right.)

**Comment by Dugy** [comment]
After this horrible merge, changing the directory structure should be a feasible option. To prevent problems, it's always a good idea to do it in a small commit without any changes to the files.

I have been using Google Test previously, but I can't say I have good experience with it. I found the ad hoc test code more convenient to work with than dealing with some of the annoyances of Google Test.

**Comment by rpatters1** [comment]
My request would be that you keep `prerebase_master` as a c++17 compatibility branch and drop support for c++17 going forward. Perhaps rename it to something more appropriate: a version number or `cpp17_compatibility_branch`. The new code is too reliant on C++20 features to maintain backwards compatibility easily, especially in some of the template parameters. The only other option would be to use #ifdef to remove swatches of it that use the new templates, but I don't know if that's possible.

Meanwhile, even the C++20 version is not compiling for me on macOS. I have isolated a single line that is the remaining problem:

```
		constexpr static int BlockCount = std::max(section.MaxSize / BlockSize, 1);
```

For some reason my macOS compiler doesn't think this is constexpr.

**Comment by rpatters1** [comment]
Lol, MSVC is complaining about a *different* `constexpr` declaration:

```
constexpr static bool noneGreaterThanEight = checkIfNoneGreaterThanEight<0>();
```

It seems like we are on the C++20 bleeding edge here.

**Comment by Dugy** [comment]
I think that the problem is just that `checkIfNoneGreaterThanEight()` isn't declared as `constexpr`.

**Comment by rpatters1** [comment]
I'm working on PR with several updates to make it compile on C++20 (for me).

**Comment by Dugy** [comment]
I am working on fixes for C++17 currently.

**Comment by rpatters1** [comment]
I started down that path, but got stuck at the template initializers.

Would you like me to back off until you've done what you're doing?

**Comment by Dugy** [comment]
I am close to being done with the C++17 part, so what you're doing there might be unnecessary, but the changes I am making probably won't make too many merge conflicts with the MSVC and AppleClang changes.

**Comment by rpatters1** [comment]
I got it to build on macOS. This line:

```
Block& operator=(const Block& other) = default;
```
is getting a deprecated warning. Apparently if a class has a user-declared copy assignment operator it (in the future) can't have an implicit copy assignment operator. I'm thinking this line may just need to be deleted.

**Comment by rpatters1** [comment]
The ezgz_test program crashes on Windows because by default it has too small a stack to handle the `main` function. I'm thinking it would be wise to move some of those buffers to the heap.

**Comment by Dugy** [comment]
> I'm thinking this line may just need to be deleted.

Could be. If it works without it, it's okay to delete it.

> The ezgz_test program crashes on Windows because by default it has too small a stack to handle the main function. I'm thinking it would be wise to move some of those buffers to the heap.

I though all major OSes had default stack size of 8 MiB. I think the part to blame here is `MultiIndexBloomFilter`. It takes the buffer size as template parameter, you can try reducing it if it will work. This class is rather bad overall and I want to replace it entirely.

**Comment by rpatters1** [comment]
Window frequently shows its 90s (or even 80s sometimes) roots, and this is one such place. I think it defaults to a 500K stack or some such. Anyway, I modified CMakeLists.txt to give it 8MB and now it works.

I now have both macOS and windows running for C++20 without errors or warnings. I'll wait for your PR merge and then rebase what I've got on that before submitting another PR.

**Comment by Dugy** [comment]
Don't wait for me to finish the C++17 part, I don't think I will be able to finish the last issues today.

**Comment by Dugy** [comment]
I managed to finish it. Now the tests are passing.

**Pull request merged**
