### PR TITLE
Suppress VS Code yaml warnings

### PR DESCRIPTION
**Pull request by rpatters1**
I installed the GitHub Workflow extension for VS Code, and it lit up several warnings. This PR suppresses the warnings.

I also changed the name of the workflow to `EzGz Tests`.

### CODE REVIEW

**Comment by Dugy** [comment]
Give me some time please, I really need to finish rebasing my branch and your changes have introduced a lot of trouble there

**Comment by rpatters1** [comment]
No worries at all. I'm sorry I didn't catch these warnings before.

I am extremely grateful to your flexibility so far. This project is exactly what I needed, so you've really helped me out. The only change here is a couple of lines in the `.yml` file. They'll keep until you're ready.

**Comment by Dugy** [comment]
The merge conflicts were so significant that I had to apply your changes on top of my changes, often manually, and then force push the rest. I am sorry for the inconvenience, I shouldn't even have allowed you to make the commits before merging my half-done work into it.

It has broken some C++17 compatibility and some MSVC compatibility. I don't have access to MSVC, so I will need your help with that.

**Comment by rpatters1** [comment]
I'm closing this in favor of #11.

**Pull request closed without merging**
